version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changethisnow69asrielwarnuaboutthis420teriteri
    volumes:
      - ./mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081/tcp
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: changethisnow69asrielwarnuaboutthis420teriteri
      ME_CONFIG_MONGODB_URL: mongodb://root:changethisnow69asrielwarnuaboutthis420teriteri@mongo:27017/

  grasscutter:
    image: ghcr.io/joshua-noakes1/grasscutters-docker
    container_name: grasscutter
    stdin_open: true
    tty: true
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8888:8888/tcp
      - 22102:22102/udp
    volumes:
      - ./data:/root/grass/data
      - ./web:/root/grass/web
      - ./plugins:/root/grass/plugins
      - ./config.json:/root/grass/config.json
      - ./keystore.p12:/root/grass/keystore.p12
