# Build docker buildx for AMD64, Arm64 and ArmV7
name: Build Server

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/**.md'
      - '**/**.yml'    
      - '**/**.json'
      - '!**/build.yml'
env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Docker sha tag
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha
      - name: Extract Docker latest tag
        id: meta-latest
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=raw, value=latest   

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./server/alpine
          file: ./server/dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.REGISTRY_GHCR }}/${{ steps.meta-latest.outputs.tags }}
            ${{ env.REGISTRY_GHCR }}/${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha
